//
//  389_find_difference.swift
//  stop
//
//  Created by Kostiantyn Madiar on 25/09/2023.
//

import Foundation

/*
 389. Find the Difference
 Easy
 You are given two strings s and t.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Return the letter that was added to t.



 Example 1:

 Input: s = "abcd", t = "abcde"
 Output: "e"
 Explanation: 'e' is the letter that was added.
 Example 2:

 Input: s = "", t = "y"
 Output: "y"


 Constraints:

 0 <= s.length <= 1000
 t.length == s.length + 1
 s and t consist of lowercase English letters.
 */

enum __389 {
    class Solution {
        func findTheDifference(_ s: String, _ t: String) -> Character {
            let sortedS = Array(s).sorted()
            let sortedT = Array(t).sorted()

            for index in 0..<sortedS.count {
                if sortedS[index] != sortedT[index] {
                    return sortedT[index]
                }
            }

            return sortedT.last!
        }
    }
}
